package com.vitaflow.app.presentation.ui.features.capture

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.vitaflow.app.domain.models.Food
import com.vitaflow.app.domain.usecase.nutrition.AddFoodEntryUseCase
import com.vitaflow.app.domain.usecase.nutrition.AnalyzeFoodImageUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.io.InputStream
import javax.inject.Inject

private const val TAG = "PhotoCaptureViewModel"

@HiltViewModel
class PhotoCaptureViewModel @Inject constructor(
    private val analyzeFoodImageUseCase: AnalyzeFoodImageUseCase,
    private val addFoodEntryUseCase: AddFoodEntryUseCase
) : ViewModel() {

    private val _state = MutableStateFlow(PhotoCaptureState())
    val state: StateFlow<PhotoCaptureState> = _state.asStateFlow()

    private val _events = MutableSharedFlow<PhotoCaptureEvent>()
    val events: SharedFlow<PhotoCaptureEvent> = _events.asSharedFlow()

    fun onImageCaptured(bitmap: Bitmap) {
        Log.d(TAG, "Image captured, starting analysis")
        _state.update { it.copy(capturedBitmap = bitmap, isAnalyzing = true) }
        analyzeImage(bitmap)
    }

    fun onImageSelected(context: Context, uri: Uri) {
        viewModelScope.launch {
            try {
                val inputStream: InputStream? = context.contentResolver.openInputStream(uri)
                val bitmap = BitmapFactory.decodeStream(inputStream)
                inputStream?.close()

                if (bitmap != null) {
                    Log.d(TAG, "Image selected from gallery, starting analysis")
                    _state.update { it.copy(capturedBitmap = bitmap, isAnalyzing = true) }
                    analyzeImage(bitmap)
                } else {
                    _events.emit(PhotoCaptureEvent.ShowError("Failed to load image"))
                }
            } catch (e: Exception) {
                Log.e(TAG, "Error loading image from gallery", e)
                _events.emit(PhotoCaptureEvent.ShowError("Failed to load image: ${e.message}"))
            }
        }
    }

    private fun analyzeImage(bitmap: Bitmap) {
        viewModelScope.launch {
            try {
                Log.d(TAG, "Analyzing food image...")

                analyzeFoodImageUseCase(bitmap).fold(
                    onSuccess = { result ->
                        Log.d(TAG, "Analysis successful: ${result.foodName}")
                        _state.update {
                            it.copy(
                                analysisResult = result,
                                isAnalyzing = false
                            )
                        }
                    },
                    onFailure = { error ->
                        Log.e(TAG, "Analysis failed", error)
                        _state.update { it.copy(isAnalyzing = false) }
                        _events.emit(
                            PhotoCaptureEvent.ShowError(
                                "Failed to analyze image: ${error.message}"
                            )
                        )
                    }
                )
            } catch (e: Exception) {
                Log.e(TAG, "Error analyzing image", e)
                _state.update { it.copy(isAnalyzing = false) }
                _events.emit(PhotoCaptureEvent.ShowError("Error: ${e.message}"))
            }
        }
    }

    fun updateMealType(mealType: String) {
        _state.update { it.copy(selectedMealType = mealType) }
    }

    fun updateQuantity(quantity: Double) {
        _state.update { it.copy(quantity = quantity) }
    }

    fun saveFoodEntry(mealType: String, quantity: Double) {
        viewModelScope.launch {
            val analysisResult = _state.value.analysisResult

            if (analysisResult == null) {
                _events.emit(PhotoCaptureEvent.ShowError("No food analysis available"))
                return@launch
            }

            try {
                Log.d(TAG, "Saving food entry: ${analysisResult.foodName}, Meal: $mealType, Quantity: $quantity")

                // Convert analysis result to Food object
                // Create Food object - adjust fields based on your Food model
                val food = Food(
                    id = 0, // Will be generated by the database
                    name = analysisResult.foodName,
                    caloriesPer100g = analysisResult.caloriesPer100g,
                    carbsPer100g = analysisResult.carbsPer100g,
                    proteinPer100g = analysisResult.proteinPer100g,
                    fatPer100g = analysisResult.fatPer100g,
                    imageUrl = null,
                    barcode = null
                    // Add other required fields from your Food model
                )

                addFoodEntryUseCase(food, mealType, quantity).fold(
                    onSuccess = {
                        Log.d(TAG, "Food entry saved successfully")
                        _events.emit(PhotoCaptureEvent.FoodSaved)
                    },
                    onFailure = { error ->
                        Log.e(TAG, "Failed to save food entry", error)
                        _events.emit(
                            PhotoCaptureEvent.ShowError(
                                "Failed to save: ${error.message}"
                            )
                        )
                    }
                )
            } catch (e: Exception) {
                Log.e(TAG, "Error saving food entry", e)
                _events.emit(PhotoCaptureEvent.ShowError("Error saving: ${e.message}"))
            }
        }
    }

    fun resetCapture() {
        _state.update {
            PhotoCaptureState()
        }
    }
}

// State
data class PhotoCaptureState(
    val capturedBitmap: Bitmap? = null,
    val analysisResult: FoodAnalysisResult? = null,
    val isAnalyzing: Boolean = false,
    val selectedMealType: String = "breakfast",
    val quantity: Double = 100.0
)

// Analysis Result
data class FoodAnalysisResult(
    val foodName: String,
    val calories: Int,
    val carbs: Int,
    val protein: Int,
    val fat: Int,
    val caloriesPer100g: Double,
    val carbsPer100g: Double?,
    val proteinPer100g: Double,
    val fatPer100g: Double,
    val confidence: Float = 0.85f
)

// Events
sealed class PhotoCaptureEvent {
    object NavigateBack : PhotoCaptureEvent()
    object FoodSaved : PhotoCaptureEvent()
    data class ShowError(val message: String) : PhotoCaptureEvent()
}